#include "functions.hpp"

#define DECLARE_PROC(TYPE, NAME) TYPE NAME;
#define GET_PROC_ADDR(TYPE, NAME) NAME = (TYPE) wglGetProcAddress(#NAME);

DECLARE_PROC(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB)
DECLARE_PROC(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB)
DECLARE_PROC(PFNGLCREATEPROGRAMPROC, glCreateProgram)

void LoadGlFunctions()
{
    GET_PROC_ADDR(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB)
    GET_PROC_ADDR(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB)
    GET_PROC_ADDR(PFNGLCREATEPROGRAMPROC, glCreateProgram)
}
